OAuth2\ServerBundle\Entity\Scope:
    type: entity
    table: oauth_scope
    id:
        scope:
            type:       string
            length:     255
            column:     id
    fields:
        description:
            type:       string
            length:     255
            column:     field
    lifecycleCallbacks: {  }
